services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://anamny_user:anamny_password@db:5432/anamny_db
      - SECRET_KEY=your-secret-key-change-this-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=anamny_user
      - POSTGRES_PASSWORD=anamny_password
      - POSTGRES_DB=anamny_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anamny_user -d anamny_db"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: